/**
 * GENERATED by scripts/build-images.mjs — do not edit by hand.
 *
 * Intrinsic dimensions and srcsets for every catalogue image. Importing from
 * here means markup can never ship an <img> without width/height, which is the
 * only defence against layout shift on a stack with no runtime image pipeline.
 */
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  srcSet: string;
};

export const images = {
  "bridal-tikka-front": {
    "src": "/images/catalogue/bridal-tikka-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/bridal-tikka-front-400.webp 400w, /images/catalogue/bridal-tikka-front-800.webp 800w, /images/catalogue/bridal-tikka-front-1400.webp 1400w"
  },
  "bridal-tikka-reverse": {
    "src": "/images/catalogue/bridal-tikka-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/bridal-tikka-reverse-400.webp 400w, /images/catalogue/bridal-tikka-reverse-800.webp 800w, /images/catalogue/bridal-tikka-reverse-1400.webp 1400w"
  },
  "bridal-tikka-worn": {
    "src": "/images/catalogue/bridal-tikka-worn-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/bridal-tikka-worn-400.webp 400w, /images/catalogue/bridal-tikka-worn-800.webp 800w, /images/catalogue/bridal-tikka-worn-1400.webp 1400w"
  },
  "founder-portrait-a": {
    "src": "/images/catalogue/founder-portrait-a-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/founder-portrait-a-400.webp 400w, /images/catalogue/founder-portrait-a-900.webp 900w"
  },
  "founder-portrait-b": {
    "src": "/images/catalogue/founder-portrait-b-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/founder-portrait-b-400.webp 400w, /images/catalogue/founder-portrait-b-900.webp 900w"
  },
  "founder-saksham-goel": {
    "src": "/images/catalogue/founder-saksham-goel-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/founder-saksham-goel-400.webp 400w, /images/catalogue/founder-saksham-goel-900.webp 900w"
  },
  "gold-jhumka-front": {
    "src": "/images/catalogue/gold-jhumka-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/gold-jhumka-front-400.webp 400w, /images/catalogue/gold-jhumka-front-800.webp 800w, /images/catalogue/gold-jhumka-front-1400.webp 1400w"
  },
  "gold-jhumka-reverse": {
    "src": "/images/catalogue/gold-jhumka-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/gold-jhumka-reverse-400.webp 400w, /images/catalogue/gold-jhumka-reverse-800.webp 800w, /images/catalogue/gold-jhumka-reverse-1400.webp 1400w"
  },
  "gold-jhumka-worn": {
    "src": "/images/catalogue/gold-jhumka-worn-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/gold-jhumka-worn-400.webp 400w, /images/catalogue/gold-jhumka-worn-800.webp 800w, /images/catalogue/gold-jhumka-worn-1400.webp 1400w"
  },
  "jadau-kangan-front": {
    "src": "/images/catalogue/jadau-kangan-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/jadau-kangan-front-400.webp 400w, /images/catalogue/jadau-kangan-front-800.webp 800w, /images/catalogue/jadau-kangan-front-1400.webp 1400w"
  },
  "jadau-kangan-reverse": {
    "src": "/images/catalogue/jadau-kangan-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/jadau-kangan-reverse-400.webp 400w, /images/catalogue/jadau-kangan-reverse-800.webp 800w, /images/catalogue/jadau-kangan-reverse-1400.webp 1400w"
  },
  "jadau-kangan-worn": {
    "src": "/images/catalogue/jadau-kangan-worn-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/jadau-kangan-worn-400.webp 400w, /images/catalogue/jadau-kangan-worn-800.webp 800w, /images/catalogue/jadau-kangan-worn-1400.webp 1400w"
  },
  "lotus-pendant-front": {
    "src": "/images/catalogue/lotus-pendant-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/lotus-pendant-front-400.webp 400w, /images/catalogue/lotus-pendant-front-800.webp 800w, /images/catalogue/lotus-pendant-front-1400.webp 1400w"
  },
  "lotus-pendant-reverse": {
    "src": "/images/catalogue/lotus-pendant-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/lotus-pendant-reverse-400.webp 400w, /images/catalogue/lotus-pendant-reverse-800.webp 800w, /images/catalogue/lotus-pendant-reverse-1400.webp 1400w"
  },
  "lotus-pendant-worn": {
    "src": "/images/catalogue/lotus-pendant-worn-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/lotus-pendant-worn-400.webp 400w, /images/catalogue/lotus-pendant-worn-800.webp 800w, /images/catalogue/lotus-pendant-worn-1400.webp 1400w"
  },
  "medallion-temple-haar-front": {
    "src": "/images/catalogue/medallion-temple-haar-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/medallion-temple-haar-front-400.webp 400w, /images/catalogue/medallion-temple-haar-front-800.webp 800w, /images/catalogue/medallion-temple-haar-front-1400.webp 1400w"
  },
  "meenakari-bridal-choker-front": {
    "src": "/images/catalogue/meenakari-bridal-choker-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/meenakari-bridal-choker-front-400.webp 400w, /images/catalogue/meenakari-bridal-choker-front-800.webp 800w, /images/catalogue/meenakari-bridal-choker-front-1400.webp 1400w"
  },
  "parrot-temple-haar-front": {
    "src": "/images/catalogue/parrot-temple-haar-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/parrot-temple-haar-front-400.webp 400w, /images/catalogue/parrot-temple-haar-front-800.webp 800w, /images/catalogue/parrot-temple-haar-front-1400.webp 1400w"
  },
  "peacock-temple-haar-front": {
    "src": "/images/catalogue/peacock-temple-haar-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/peacock-temple-haar-front-400.webp 400w, /images/catalogue/peacock-temple-haar-front-800.webp 800w, /images/catalogue/peacock-temple-haar-front-1400.webp 1400w"
  },
  "polki-ring-front": {
    "src": "/images/catalogue/polki-ring-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/polki-ring-front-400.webp 400w, /images/catalogue/polki-ring-front-800.webp 800w, /images/catalogue/polki-ring-front-1400.webp 1400w"
  },
  "polki-ring-worn": {
    "src": "/images/catalogue/polki-ring-worn-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/polki-ring-worn-400.webp 400w, /images/catalogue/polki-ring-worn-800.webp 800w, /images/catalogue/polki-ring-worn-1400.webp 1400w"
  },
  "rani-haar-front": {
    "src": "/images/catalogue/rani-haar-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/rani-haar-front-400.webp 400w, /images/catalogue/rani-haar-front-800.webp 800w, /images/catalogue/rani-haar-front-1400.webp 1400w"
  },
  "rani-haar-reverse": {
    "src": "/images/catalogue/rani-haar-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/rani-haar-reverse-400.webp 400w, /images/catalogue/rani-haar-reverse-800.webp 800w, /images/catalogue/rani-haar-reverse-1400.webp 1400w"
  },
  "rani-haar-worn": {
    "src": "/images/catalogue/rani-haar-worn-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/rani-haar-worn-400.webp 400w, /images/catalogue/rani-haar-worn-800.webp 800w, /images/catalogue/rani-haar-worn-1400.webp 1400w"
  },
  "slim-kada-front": {
    "src": "/images/catalogue/slim-kada-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/slim-kada-front-400.webp 400w, /images/catalogue/slim-kada-front-800.webp 800w, /images/catalogue/slim-kada-front-1400.webp 1400w"
  },
  "slim-kada-worn": {
    "src": "/images/catalogue/slim-kada-worn-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/slim-kada-worn-400.webp 400w, /images/catalogue/slim-kada-worn-800.webp 800w, /images/catalogue/slim-kada-worn-1400.webp 1400w"
  },
  "temple-arch-haar-front": {
    "src": "/images/catalogue/temple-arch-haar-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/temple-arch-haar-front-400.webp 400w, /images/catalogue/temple-arch-haar-front-800.webp 800w, /images/catalogue/temple-arch-haar-front-1400.webp 1400w"
  },
  "workshop-bench": {
    "src": "/images/catalogue/workshop-bench-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/workshop-bench-400.webp 400w, /images/catalogue/workshop-bench-900.webp 900w"
  },
  "workshop-hands": {
    "src": "/images/catalogue/workshop-hands-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/workshop-hands-400.webp 400w, /images/catalogue/workshop-hands-900.webp 900w"
  }
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof images;
