/**
 * GENERATED by scripts/build-images.mjs — do not edit by hand.
 *
 * Intrinsic dimensions and srcsets for every catalogue image. Importing from
 * here means markup can never ship an <img> without width/height, which is the
 * only defence against layout shift on a stack with no runtime image pipeline.
 */
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  srcSet: string;
};

export const images = {
  "chandbali-earrings-front": {
    "src": "/images/catalogue/chandbali-earrings-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/chandbali-earrings-front-400.webp 400w, /images/catalogue/chandbali-earrings-front-800.webp 800w, /images/catalogue/chandbali-earrings-front-1400.webp 1400w"
  },
  "chandbali-earrings-reverse": {
    "src": "/images/catalogue/chandbali-earrings-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/chandbali-earrings-reverse-400.webp 400w, /images/catalogue/chandbali-earrings-reverse-800.webp 800w, /images/catalogue/chandbali-earrings-reverse-1400.webp 1400w"
  },
  "founder-portrait-a": {
    "src": "/images/catalogue/founder-portrait-a-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/founder-portrait-a-400.webp 400w, /images/catalogue/founder-portrait-a-900.webp 900w"
  },
  "founder-portrait-b": {
    "src": "/images/catalogue/founder-portrait-b-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/founder-portrait-b-400.webp 400w, /images/catalogue/founder-portrait-b-900.webp 900w"
  },
  "jadau-haar-front": {
    "src": "/images/catalogue/jadau-haar-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/jadau-haar-front-400.webp 400w, /images/catalogue/jadau-haar-front-800.webp 800w, /images/catalogue/jadau-haar-front-1400.webp 1400w"
  },
  "jadau-haar-reverse": {
    "src": "/images/catalogue/jadau-haar-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/jadau-haar-reverse-400.webp 400w, /images/catalogue/jadau-haar-reverse-800.webp 800w, /images/catalogue/jadau-haar-reverse-1400.webp 1400w"
  },
  "kundan-kada-front": {
    "src": "/images/catalogue/kundan-kada-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/kundan-kada-front-400.webp 400w, /images/catalogue/kundan-kada-front-800.webp 800w, /images/catalogue/kundan-kada-front-1400.webp 1400w"
  },
  "kundan-kada-reverse": {
    "src": "/images/catalogue/kundan-kada-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/kundan-kada-reverse-400.webp 400w, /images/catalogue/kundan-kada-reverse-800.webp 800w, /images/catalogue/kundan-kada-reverse-1400.webp 1400w"
  },
  "maang-tikka-front": {
    "src": "/images/catalogue/maang-tikka-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/maang-tikka-front-400.webp 400w, /images/catalogue/maang-tikka-front-800.webp 800w, /images/catalogue/maang-tikka-front-1400.webp 1400w"
  },
  "maang-tikka-reverse": {
    "src": "/images/catalogue/maang-tikka-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/maang-tikka-reverse-400.webp 400w, /images/catalogue/maang-tikka-reverse-800.webp 800w, /images/catalogue/maang-tikka-reverse-1400.webp 1400w"
  },
  "polki-choker-front": {
    "src": "/images/catalogue/polki-choker-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/polki-choker-front-400.webp 400w, /images/catalogue/polki-choker-front-800.webp 800w, /images/catalogue/polki-choker-front-1400.webp 1400w"
  },
  "polki-choker-reverse": {
    "src": "/images/catalogue/polki-choker-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/polki-choker-reverse-400.webp 400w, /images/catalogue/polki-choker-reverse-800.webp 800w, /images/catalogue/polki-choker-reverse-1400.webp 1400w"
  },
  "rani-haar-front": {
    "src": "/images/catalogue/rani-haar-front-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/rani-haar-front-400.webp 400w, /images/catalogue/rani-haar-front-800.webp 800w, /images/catalogue/rani-haar-front-1400.webp 1400w"
  },
  "rani-haar-reverse": {
    "src": "/images/catalogue/rani-haar-reverse-1400.webp",
    "width": 1400,
    "height": 1750,
    "srcSet": "/images/catalogue/rani-haar-reverse-400.webp 400w, /images/catalogue/rani-haar-reverse-800.webp 800w, /images/catalogue/rani-haar-reverse-1400.webp 1400w"
  },
  "workshop-bench": {
    "src": "/images/catalogue/workshop-bench-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/workshop-bench-400.webp 400w, /images/catalogue/workshop-bench-900.webp 900w"
  },
  "workshop-hands": {
    "src": "/images/catalogue/workshop-hands-900.webp",
    "width": 900,
    "height": 1125,
    "srcSet": "/images/catalogue/workshop-hands-400.webp 400w, /images/catalogue/workshop-hands-900.webp 900w"
  }
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof images;
