/**
 * Build web-ready image derivatives from the catalogue masters.
 *
 * WHY THIS EXISTS: `next/image` does not work on this deployment. `worker/index.ts`
 * routes /_vinext/image through `env.IMAGES`, but `vite.config.ts` never declares
 * that binding, so the optimizer throws before it can even report an error (see
 * research/01-codebase.md). There is therefore no runtime image optimisation and
 * no automatic srcset — every derivative has to be produced ahead of time.
 *
 * Masters live in design/generated/ (PNG, 1024x1280, ~2 MB each) and are NOT
 * served. This writes sized WebP into public/images/catalogue/ plus a manifest
 * the app imports so markup can emit correct width/height/srcset and never
 * guess at intrinsic dimensions.
 *
 * Usage: node scripts/build-images.mjs
 */
import { execFileSync } from "node:child_process";
import { mkdir, readdir, writeFile, stat } from "node:fs/promises";
import path from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const SRC = path.join(ROOT, "design/generated");
const OUT = path.join(ROOT, "public/images/catalogue");

/** Rendered widths. 4:5 portrait, so height is width * 1.25. */
const WIDTHS = [400, 800, 1400];
const QUALITY = 82;

/** Masters that are not catalogue pieces get their own treatment. */
const EDITORIAL = new Set(["founder-portrait-a", "founder-portrait-b", "founder-saksham-goel", "workshop-bench", "workshop-hands"]);

function magick(args) {
  execFileSync("magick", args, { stdio: "pipe" });
}

const files = (await readdir(SRC))
  .filter((f) => f.endsWith(".png") && !f.startsWith("test-"))
  .sort();

if (!files.length) {
  console.error("No masters found in design/generated/");
  process.exit(1);
}

await mkdir(OUT, { recursive: true });

const manifest = {};
let masterBytes = 0;
let outBytes = 0;

for (const file of files) {
  const slug = file.replace(/\.png$/, "");
  const src = path.join(SRC, file);
  masterBytes += (await stat(src)).size;

  const widths = EDITORIAL.has(slug) ? [400, 900] : WIDTHS;
  const sources = [];

  for (const w of widths) {
    const h = Math.round(w * 1.25);
    const outFile = `${slug}-${w}.webp`;
    magick([
      src,
      "-colorspace", "RGB",
      "-filter", "Lanczos",
      "-resize", `${w}x${h}!`,
      "-colorspace", "sRGB",
      "-strip",
      "-define", `webp:method=6`,
      "-quality", String(QUALITY),
      path.join(OUT, outFile),
    ]);
    const size = (await stat(path.join(OUT, outFile))).size;
    outBytes += size;
    sources.push({ width: w, height: h, file: outFile, bytes: size });
  }

  const largest = sources[sources.length - 1];
  manifest[slug] = {
    src: `/images/catalogue/${largest.file}`,
    width: largest.width,
    height: largest.height,
    srcSet: sources.map((s) => `/images/catalogue/${s.file} ${s.width}w`).join(", "),
    sources,
  };

  console.log(
    `${slug.padEnd(28)} ${sources.map((s) => `${s.width}w:${(s.bytes / 1024).toFixed(0)}KB`).join("  ")}`
  );
}

const ts = `/**
 * GENERATED by scripts/build-images.mjs — do not edit by hand.
 *
 * Intrinsic dimensions and srcsets for every catalogue image. Importing from
 * here means markup can never ship an <img> without width/height, which is the
 * only defence against layout shift on a stack with no runtime image pipeline.
 */
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  srcSet: string;
};

export const images = ${JSON.stringify(
  Object.fromEntries(
    Object.entries(manifest).map(([k, v]) => [k, { src: v.src, width: v.width, height: v.height, srcSet: v.srcSet }])
  ),
  null,
  2
)} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof images;
`;

await writeFile(path.join(ROOT, "app/_media/images.ts"), ts);

console.log(
  `\nmasters ${(masterBytes / 1024 / 1024).toFixed(1)} MB  ->  derivatives ${(outBytes / 1024 / 1024).toFixed(1)} MB` +
    `  (${files.length} masters, ${Object.values(manifest).reduce((n, m) => n + m.sources.length, 0)} files)`
);
console.log("wrote app/_media/images.ts");
