import { writeFile, mkdir } from "node:fs/promises";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const OUT = "/Users/architjain/alankar-jewellers/public/fonts";
const WANTED = new Set(["latin", "latin-ext"]);

const FAMILIES = [
  // Display. Indian Type Foundry, high-contrast, Devanagari-rooted Latin.
  // Regal without being a Didone, which is the face every luxury template uses.
  { name: "Rozha One", spec: "Rozha+One", slug: "rozha" },
  // Body. Also ITF, drawn alongside its own Devanagari, so a Hindi line later
  // sets natively in the same voice.
  { name: "Karma", spec: "Karma:wght@300;400;500;600;700", slug: "karma" },
  // Data only: weights, karat, HUID, rates, order ids.
  { name: "IBM Plex Mono", spec: "IBM+Plex+Mono:wght@400;500", slug: "plex-mono" },
];

await mkdir(OUT, { recursive: true });
const faces = [];
let bytes = 0;

for (const family of FAMILIES) {
  const css = await (
    await fetch(`https://fonts.googleapis.com/css2?family=${family.spec}&display=swap`, {
      headers: { "User-Agent": UA },
    })
  ).text();

  // Each @font-face is preceded by a /* subset */ comment.
  const blocks = css.split("/*").slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    if (!WANTED.has(subset)) continue;

    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!weight || !url) continue;

    const file = `${family.slug}-${weight}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    await writeFile(`${OUT}/${file}`, buf);
    bytes += buf.length;

    faces.push({ family: family.name, weight, file, range, subset, size: buf.length });
    console.log(`${file.padEnd(34)} ${String(buf.length).padStart(7)} B`);
  }
}

const css = `/**
 * Self-hosted typefaces for the "Meena Reverse" direction.
 *
 * Eczar        — display. A Devanagari face with a matching Latin (Rosetta,
 *                Vaibhav Singh, OFL). Indian type authorship, not a Latin serif
 *                with Devanagari bolted on, and nothing like the Playfair/Bodoni
 *                default the old site used.
 * Mukta        — body/UI. Humanist sans drawn alongside its own Devanagari
 *                (Ek Type, OFL), so a Hindi line later sets in the same voice.
 * IBM Plex Mono — data only: weights, karat, HUID, gold rate, order ids.
 *
 * latin + latin-ext subsets only. Generated by scripts/fetch-fonts.mjs.
 * Total: ${(bytes / 1024).toFixed(1)} KB across ${faces.length} files.
 */

${faces
  .map(
    (f) => `@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url("/fonts/${f.file}") format("woff2");
  unicode-range: ${f.range};
}`
  )
  .join("\n\n")}
`;

await writeFile("/Users/architjain/alankar-jewellers/app/fonts.css", css);
console.log(`\nTOTAL: ${(bytes / 1024).toFixed(1)} KB across ${faces.length} files`);
console.log("wrote app/fonts.css");
